name: Build Firefox on macOS

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Install Mercurial
        run: python3 -m pip install mercurial==6.1.4

      - name: Bootstrap Mozilla Source
        run: |
          curl https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py -O
          python3 bootstrap.py --application-choice=browser --no-interactive

      - name: Update Local Source
        working-directory: ./mozilla-unified
        run: hg up -C esr115

      - name: Initialize `mozconfig`
        working-directory: ./mozilla-unified
        run: |
          echo 'ac_add_options --with-branding=browser/branding/unofficial' > mozconfig
          echo 'ac_add_options --disable-updater' >> mozconfig
          echo 'ac_add_options --disable-tests' >> mozconfig
          echo 'ac_add_options --disable-crashreporter' >> mozconfig
          echo 'export CC="$HOME"/.mozbuild/clang/bin/clang' >> mozconfig
          echo 'export CXX="$HOME"/.mozbuild/clang/bin/clang++' >> mozconfig
          perl -pi -e 's/debuggerStatement\(\) {/debuggerStatement\(\) {return null\(\);/g' ./js/src/frontend/Parser.cpp
          # rustup target add aarch64-apple-darwin
          # echo 'ac_add_options --target=aarch64-apple-darwin' >> mozconfig

      # - name: Set Release Tag Output
      #   id: release-tag
      #   run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      # - name: Construct New `debugger` Keyword
      #   id: debugger-keyword
      #   run: echo "DEBUGGER_KEYWORD=${{ inputs.debugger_keyword || format('debugger{0}', steps.release-tag.outputs.NOW) }}" >> "$GITHUB_OUTPUT"

      # - name: Replace `debugger` Keyword
      #   working-directory: ./mozilla-unified
      #   run: sed -i'' -e 's/MACRO(debugger/MACRO(${{ steps.debugger-keyword.outputs.DEBUGGER_KEYWORD }}/' ./js/src/frontend/ReservedWords.h

      - name: Build and Package
        working-directory: ./mozilla-unified
        run: |
          ./mach build 
          ./mach package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-firefox-artifacts
          path: "**/*.dmg"
